### ISSUE TITLE
README examples

### ISSUE THREAD

**Issue by brc** [Rolinh/elastic-go#1]
Hi, thanks for writing this.
Thought it would save me from having to learn the ES API or write anything myself right away.

However, I haven't been able to make a successful `query` command in about 20 minutes of trying (even after pulling up the ES API docs and learning the query language) -- what is the expected input format?  JSON?  A couple query examples in the README would help.

Probably going to move onto something else or use curl at this point.  Thought you'd like to know.

**Comment by rolinh** [comment]
Hi,

Thanks for the comment. I'll add a few sample queries in the readme file, that's a good suggestion.

**Comment by rolinh** [comment]
There is actually an example of a `query` in the README. For more, head to the Elasticsearch documentation.
